/*Non formattare il codice in automatico da errore*/

/*Usi Locali*/
INSERT INTO uso_locale (nome, descrizione) VALUES ("Medicina", "Le foglie, le radici, la corteccia e/o i frutti vengono usati nella medicina tradizionale.");
INSERT INTO uso_locale (nome, descrizione) VALUES ("Consumo e vendita","I frutti, i semi e/o le foglie vengono mangiati dalle famiglie dei contadini o venduti nei mercati locali.");
INSERT INTO uso_locale (nome, descrizione) VALUES ("Suolo",  "Migliora la qualità del suolo fissando l’azoto o riduce l'erosione grazie all'esteso apparato radicale.");
INSERT INTO uso_locale (nome, descrizione) VALUES ("Recinzione", "Permette di proteggere un’area coltivata o di dare ristoro agli animali al pascolo.");
INSERT INTO uso_locale (nome, descrizione) VALUES ("Antivento", "Protegge dal vento le giovani piante e riduce l'evaporazione dell'acqua dal suolo.");
INSERT INTO uso_locale (nome, descrizione) VALUES ("Cosmesi", "Dai suoi fiori, frutti e/o foglie si estraggono materie prime utilizzate per produrre creme o polveri.");
INSERT INTO uso_locale (nome, descrizione) VALUES ("Allevamento", "Le foglie, fresche o essiccate, vengono utilizzate come mangime per il bestiame.");
INSERT INTO uso_locale (nome, descrizione) VALUES ("Biodiversità","Facilita il ripopolamento di varie specie animali, favorendo così in generale la varietà nella fauna e nella flora.");
INSERT INTO uso_locale (nome, descrizione) VALUES ("Insetticida naturale","Le foglie e/o i frutti contengono sostanze utili contro le fitopatologie e utilizzabili come insetticidi naturali.");

/*Benefici*/
INSERT INTO beneficio (nome, descrizione) VALUES ("Sicurezza alimentare","Gli alberi daranno frutti, alcuni che saranno immediatamente commestibili e altri che potranno diventare commestibili attraverso la lavorazione, garantendo risorse alimentari nel tempo.");
INSERT INTO beneficio (nome, descrizione) VALUES ("Sviluppo economico","I frutti degli alberi e i prodotti derivati dalla loro trasformazione possono essere scambiati in reti locali, offrendo opportunità di reddito.");
INSERT INTO beneficio (nome, descrizione) VALUES ("Assorbimento di Anidride Carbonica","Durante il suo ciclo di vita, ogni albero compenserà l' anidride carbonica. Gli alberi che pianti possono compensare le tue emissioni");
INSERT INTO beneficio (nome, descrizione) VALUES ("Protezione ambientale","Gli alberi sono piantati in sistemi agroforestali che favoriscono l'interazione virtuosa tra le diverse specie e il loro impatto positivo sull'ambiente e sul territorio.");

/*Categorie*/
INSERT INTO categoria (nome, descrizione) VALUES ("Svilluppo sostenibile","L’educazione è il motore dello sviluppo sostenibile. I valori fondamentali insegnati ai bambini sono il rispetto dell’ambiente, l’uso di materiali riciclati e l’interiorizzazione di uno stile di vita sostenibile a 360°!");
INSERT INTO categoria (nome, descrizione) VALUES ("Salvaguardia ambientale","Ci addentriamo nella foresta amazzonica per recuperare sementi storici di alberi forestali, che poi coltiviamo in vivaio. Questi alberi vengono inseriti in sistemi forestali misti in cui la varietà di specie assicura la stabilità e la resilienza dell’impianto.");
INSERT INTO categoria (nome, descrizione) VALUES ("Rischio estinzione","L'albero è classificato come “in pericolo” nella Lista rossa delle specie minacciate dell’IUCN (Unione internazionale per la conservazione della natura).");

/*Paesi*/
INSERT INTO paese_origine (nome, descrizione) VALUES ("Italia","L'Italia non è solo il paese in cui WoodLot è stata fondata nel 2022, ma è anche uno dei paesi in cui piantiamo alberi. Si tratta di progetti dai numeri piuttosto contenuti, ma non per questo meno importanti. I progetti a cui diamo vita in Italia rispettano la nostra filosofia, che è quella di produrre benefici sociali e ambientali, ma la applicano ad un contesto diverso rispetto a quelli degli altri paesi in cui lavoriamo. Se i benefici ambientali si realizzano anche in Italia grazie alla piantumazione di nuovi alberi, per i benefici sociali è decisiva la scelta dei nostri partner di progetto. Questi sono associazioni, onlus, cooperative sociali (non lavoriamo con soggetti privati) che, ad esempio, includono categorie in difficoltà nelle proprie attività oppure recuperano aree confiscate alla criminalità organizzata. L'intento è quello di sostenere progetti di grande valenza sociale.");
INSERT INTO paese_origine (nome, descrizione) VALUES ("Guatemala","Il nostro lavoro in Guatemala intende realizzare molteplici benefici, tarando i progetti sulle differenti realtà territoriali e sociali con le quali lavoriamo. Come accennato, una delle zone in cui operiamo si trova nell'area rurale del Petén, nel nord del paese, qui abbiamo individuato nelle specie da frutto, il perno del nostro progetto per garantire i migliori benefici ambientali e sociali. Tra le specie di alberi che contribuiscono a creare sistemi agroforestali vi sono: Lime, Mandarino, Mango, Cacao, Graviola (conosciuta anche come Corossole o Guanàbana), Sapote (tradizionale albero da frutto assai diffuso presso le civiltà precolombiane dell'America Centrale), Guava e Arancio. Gli alberi saranno piantati in sistemi agroforestali su piccola scala, secondo i principi della permacultura, un approccio che imita i processi naturali, creando consociazioni di specie diverse.");
INSERT INTO paese_origine (nome, descrizione) VALUES ("Argentina","Il territorio dell'Argentina corre per 3.700 Km da nord a sud e per 1.400 da est a ovest. Al centro del paese sta la grande distesa pianeggiante della Pampa, intorno alla quale si trovano: la regione subtropicale del Gran Chaco a nord, il plateau della Patagonia a sud, mentre a ovest s'innalzano le maestose vette delle Ande. A tanta varietà d'ambienti corrisponde altrettanta varietà di fauna, che va dal caimano (o yacaré) al celebre condor delle Ande. L'avventura in Argentina si è svolta nelle foreste del Gran Chaco. Le risorse naturali di questa regione sono state seriamente danneggiate dalla deforestazione e abbiamo contribuito al loro ripristino, piantando alberi utili per la popolazione locale, come ad esempio l'Algarrobo.");
INSERT INTO paese_origine (nome, descrizione) VALUES ("Perù","Il Perù è un grande paese, con un enorme patrimonio naturale ed una popolazione in crescita. Crediamo che uno sviluppo sostenibile del paese non possa che passare attraverso una diffusa sensibilità verso l'ambiente ed un giusto equilibrio con l'utilizzo delle risorse che questo può offrire alle popolazioni locali.Per questo abbiamo deciso di puntare con decisione sul Perù per lo sviluppo dei nostri progetti, mirati a sviluppare tanto il lavoro di preservazione di ambienti naturali, quanto l'integrazione degli alberi nei sistemi agricoli locali.");

/*Alberi*/
INSERT INTO albero (nome, co2, descrizione, descrizione_breve, prezzo, salvaguardia, specie_scientifica, categoria, paese_origine) VALUES ("Mango", 700,"Il Mango prospera in zone tropicali e subtropicali. In pochi sanno che è in grado di raggiungere i 45 metri di altezza e produrre una gran quantità di frutti che possono essere mangiati freschi oppure lavorati ed impiegati in numerosissime ricette. Viene piantato proprio per offrire frutti alla popolazione locale, sia da consumare che da commerciare.","L'albero della felicità. Per colore, profumo e gusto, il mango è il frutto del sole e della gioia.", 29.90, 4,"Mangifera indica", "Salvaguardia ambientale", "Italia");
INSERT INTO albero_usi_locali (albero_nome, usi_locali_nome) VALUES ("Mango", "Consumo e vendita");
INSERT INTO albero_usi_locali (albero_nome, usi_locali_nome) VALUES ("Mango", "Cosmesi");
INSERT INTO albero_benefici (albero_nome, benefici_nome) VALUES ("Mango", "Sicurezza alimentare");

INSERT INTO albero (nome, co2, descrizione, descrizione_breve, prezzo, salvaguardia, specie_scientifica, categoria, paese_origine) VALUES ("Baobab", 3000,"Il Baobab è una specie originaria del Madagascar e diffusa in tutta l''Africa. Celebre per la sua imponenza, pensate che il diametro del tronco può arrivare a 10 metri. È considerato il centro gravitazionale della vita sociale dei villaggi, sotto la sua ombra si tengono mercati, riunioni, danze e giochi. Viene piantato per contribuire al recupero delle foreste naturali.","È un albero magico e senza tempo: per la sua longevità, nella tradizione popolare africana è chiamato Albero della Vita.", 59.90, 4,"Adansonia", "Rischio estinzione", "Argentina");
INSERT INTO albero_usi_locali (albero_nome, usi_locali_nome) VALUES ("Baobab", "Medicina");
INSERT INTO albero_usi_locali (albero_nome, usi_locali_nome) VALUES ("Baobab", "Biodiversità");
INSERT INTO albero_usi_locali (albero_nome, usi_locali_nome) VALUES ("Baobab", "Consumo e vendita");
INSERT INTO albero_benefici (albero_nome, benefici_nome) VALUES ("Baobab", "Protezione ambientale");

INSERT INTO albero (nome, co2, descrizione, descrizione_breve, prezzo, salvaguardia, specie_scientifica, categoria, paese_origine) VALUES ("Cacao", 55,"Il Cacao è un sempreverde che produce piccoli fiori a cinque petali, bianchi, verdi o rosei, che spuntano direttamente sul tronco o sui rami principali; i fiori più fortunati si trasformano nei celebri frutti. Viene piantato per la produzione di cacao di ottima qualità e per offrire ai contadini locali una fonte di reddito aggiuntiva.","Anche le cose apparentemente amare nascondono un animo dolce.", 19.90, 4,"Theobroma cacao", "Salvaguardia ambientale", "Argentina");
INSERT INTO albero_usi_locali (albero_nome, usi_locali_nome) VALUES ("Cacao", "Consumo e vendita");
INSERT INTO albero_benefici (albero_nome, benefici_nome) VALUES ("Cacao", "Sviluppo economico");

INSERT INTO albero (nome, co2, descrizione, descrizione_breve, prezzo, salvaguardia, specie_scientifica, categoria, paese_origine) VALUES ("Avocado", 500,"L''Avocado è principalmente conosciuto per i suoi frutti altamente energetici e ricchi di nutrienti. L''olio estratto dal frutto è usato nella cosmesi per le sue proprietà antiossidanti e rivitalizzanti, mentre le foglie hanno ottime proprietà cicatrizzanti. Viene piantato per la produzione di frutti e come albero da ombra per altre colture.","Anche le cose apparentemente amare nascondono un animo dolce.", 22.90, 4,"Persea americana", "Salvaguardia ambientale", "Perù");
INSERT INTO albero_usi_locali (albero_nome, usi_locali_nome) VALUES ("Avocado", "Cosmesi");
INSERT INTO albero_usi_locali (albero_nome, usi_locali_nome) VALUES ("Avocado", "Consumo e vendita");
INSERT INTO albero_usi_locali (albero_nome, usi_locali_nome) VALUES ("Avocado", "Biodiversità");
INSERT INTO albero_benefici (albero_nome, benefici_nome) VALUES ("Avocado", "Sviluppo economico");

INSERT INTO utente (id,nome, cognome, data_di_nascita, email, password)VALUES(1,"Alessia","Ture", '2001-02-23', "alessiature@gmail.com", "alessiature01" )